
/*
 * This file is auto-generated.
 * Do not edit directly!
 */

#ifndef SKILLS_DATABASE_H
#define SKILLS_DATABASE_H

#include <string>
#include <vector>

#include "../core/core.h"

namespace SkillsDatabase
{

using MHRBuildSearch::Skill;
using MHRBuildSearch::SetBonus;

extern const Skill g_skill_adrenaline;
extern const Skill g_skill_affinity_sliding;
extern const Skill g_skill_agitator;
extern const Skill g_skill_agitator_secret;
extern const Skill g_skill_airborne;
extern const Skill g_skill_aquatic_polar_mobility;
extern const Skill g_skill_artillery;
extern const Skill g_skill_artillery_secret;
extern const Skill g_skill_attack_boost;
extern const Skill g_skill_bbq_master;
extern const Skill g_skill_blast_attack;
extern const Skill g_skill_blast_functionality;
extern const Skill g_skill_blast_resistance;
extern const Skill g_skill_bleeding_resistance;
extern const Skill g_skill_blight_resistance;
extern const Skill g_skill_blindsider;
extern const Skill g_skill_bludgeoner;
extern const Skill g_skill_bombardier;
extern const Skill g_skill_bombardier_secret;
extern const Skill g_skill_botanist;
extern const Skill g_skill_bow_charge_plus;
extern const Skill g_skill_capacity_boost;
extern const Skill g_skill_capture_master;
extern const Skill g_skill_carving_master;
extern const Skill g_skill_carving_pro;
extern const Skill g_skill_cliffhanger;
extern const Skill g_skill_coalescence;
extern const Skill g_skill_coldproof;
extern const Skill g_skill_constitution;
extern const Skill g_skill_critical_boost;
extern const Skill g_skill_critical_draw;
extern const Skill g_skill_critical_element;
extern const Skill g_skill_critical_eye;
extern const Skill g_skill_critical_status;
extern const Skill g_skill_defense_boost;
extern const Skill g_skill_detector;
extern const Skill g_skill_divine_blessing;
extern const Skill g_skill_divine_blessing_secret;
extern const Skill g_skill_dragon_attack;
extern const Skill g_skill_dragon_resistance;
extern const Skill g_skill_dragonvein_awakening;
extern const Skill g_skill_dungmaster;
extern const Skill g_skill_earplugs;
extern const Skill g_skill_effluvia_resistance;
extern const Skill g_skill_effluvial_expert;
extern const Skill g_skill_elderseal_boost;
extern const Skill g_skill_element_acceleration;
extern const Skill g_skill_elemental_airborne;
extern const Skill g_skill_entomologist;
extern const Skill g_skill_evade_extender;
extern const Skill g_skill_evade_window;
extern const Skill g_skill_fire_attack;
extern const Skill g_skill_fire_resistance;
extern const Skill g_skill_flinch_free;
extern const Skill g_skill_focus;
extern const Skill g_skill_foragers_luck;
extern const Skill g_skill_fortify;
extern const Skill g_skill_free_elem_ammo_up;
extern const Skill g_skill_free_meal;
extern const Skill g_skill_free_meal_secret;
extern const Skill g_skill_frostcraft;
extern const Skill g_skill_full_bloom_gratitude;
extern const Skill g_skill_full_blooms_gift;
extern const Skill g_skill_gaias_veil;
extern const Skill g_skill_geologist;
extern const Skill g_skill_good_luck;
extern const Skill g_skill_gratitudes_blessing;
extern const Skill g_skill_gratitudes_gift;
extern const Skill g_skill_great_luck;
extern const Skill g_skill_guard;
extern const Skill g_skill_guard_up;
extern const Skill g_skill_guts;
extern const Skill g_skill_handicraft;
extern const Skill g_skill_hasten_recovery;
extern const Skill g_skill_health_boost;
extern const Skill g_skill_heat_guard;
extern const Skill g_skill_heavy_artillery;
extern const Skill g_skill_heroics;
extern const Skill g_skill_heroics_secret;
extern const Skill g_skill_honey_hunter;
extern const Skill g_skill_horn_maestro;
extern const Skill g_skill_hunger_resistance;
extern const Skill g_skill_ice_attack;
extern const Skill g_skill_ice_resistance;
extern const Skill g_skill_intimidator;
extern const Skill g_skill_iron_skin;
extern const Skill g_skill_item_prolonger;
extern const Skill g_skill_joys_gift;
extern const Skill g_skill_joys_gratitude;
extern const Skill g_skill_jump_master;
extern const Skill g_skill_latent_power;
extern const Skill g_skill_latent_power_secret;
extern const Skill g_skill_leap_of_faith;
extern const Skill g_skill_marathon_runner;
extern const Skill g_skill_master_fisher;
extern const Skill g_skill_master_gatherer;
extern const Skill g_skill_master_mounter;
extern const Skill g_skill_masters_touch;
extern const Skill g_skill_maximum_might;
extern const Skill g_skill_maximum_might_secret;
extern const Skill g_skill_minds_eye_ballistics;
extern const Skill g_skill_muck_resistance;
extern const Skill g_skill_mushroomancer;
extern const Skill g_skill_non_elemental_boost;
extern const Skill g_skill_normal_shots;
extern const Skill g_skill_nullify_wind_pressure;
extern const Skill g_skill_offensive_guard;
extern const Skill g_skill_palico_rally;
extern const Skill g_skill_paralysis_attack;
extern const Skill g_skill_paralysis_functionality;
extern const Skill g_skill_paralysis_resistance;
extern const Skill g_skill_partbreaker;
extern const Skill g_skill_peak_performance;
extern const Skill g_skill_piercing_shots;
extern const Skill g_skill_poison_attack;
extern const Skill g_skill_poison_duration_up;
extern const Skill g_skill_poison_functionality;
extern const Skill g_skill_poison_resistance;
extern const Skill g_skill_power_prolonger;
extern const Skill g_skill_pro_transporter;
extern const Skill g_skill_protective_polish;
extern const Skill g_skill_provoker;
extern const Skill g_skill_punishing_draw;
extern const Skill g_skill_quick_sheath;
extern const Skill g_skill_razor_sharp_spare_shot;
extern const Skill g_skill_recovery_speed;
extern const Skill g_skill_recovery_up;
extern const Skill g_skill_resentment;
extern const Skill g_skill_resuscitate;
extern const Skill g_skill_safe_landing;
extern const Skill g_skill_scenthound;
extern const Skill g_skill_scholar;
extern const Skill g_skill_scoutfly_range_up;
extern const Skill g_skill_sleep_attack;
extern const Skill g_skill_sleep_functionality;
extern const Skill g_skill_sleep_resistance;
extern const Skill g_skill_slinger_ammo_secret;
extern const Skill g_skill_slinger_capacity;
extern const Skill g_skill_slugger;
extern const Skill g_skill_slugger_secret;
extern const Skill g_skill_special_ammo_boost;
extern const Skill g_skill_speed_crawler;
extern const Skill g_skill_speed_eating;
extern const Skill g_skill_speed_sharpening;
extern const Skill g_skill_spread_power_shots;
extern const Skill g_skill_stamina_cap_up;
extern const Skill g_skill_stamina_surge;
extern const Skill g_skill_stamina_thief;
extern const Skill g_skill_stamina_thief_secret;
extern const Skill g_skill_stealth;
extern const Skill g_skill_stun_resistance;
extern const Skill g_skill_super_recovery;
extern const Skill g_skill_survival_expert;
extern const Skill g_skill_thunder_attack;
extern const Skill g_skill_thunder_resistance;
extern const Skill g_skill_tool_specialist;
extern const Skill g_skill_tool_specialist_secret;
extern const Skill g_skill_tremor_resistance;
extern const Skill g_skill_true_critical_element;
extern const Skill g_skill_true_critical_status;
extern const Skill g_skill_true_dragonvein_awakening;
extern const Skill g_skill_true_element_acceleration;
extern const Skill g_skill_true_gaias_veil;
extern const Skill g_skill_true_razor_sharp_spare_shot;
extern const Skill g_skill_water_attack;
extern const Skill g_skill_water_resistance;
extern const Skill g_skill_weakness_exploit;
extern const Skill g_skill_wide_range;
extern const Skill g_skill_windproof;

constexpr std::size_t g_skillnid_adrenaline = 0;
constexpr std::size_t g_skillnid_affinity_sliding = 1;
constexpr std::size_t g_skillnid_agitator = 2;
constexpr std::size_t g_skillnid_agitator_secret = 3;
constexpr std::size_t g_skillnid_airborne = 4;
constexpr std::size_t g_skillnid_aquatic_polar_mobility = 5;
constexpr std::size_t g_skillnid_artillery = 6;
constexpr std::size_t g_skillnid_artillery_secret = 7;
constexpr std::size_t g_skillnid_attack_boost = 8;
constexpr std::size_t g_skillnid_bbq_master = 9;
constexpr std::size_t g_skillnid_blast_attack = 10;
constexpr std::size_t g_skillnid_blast_functionality = 11;
constexpr std::size_t g_skillnid_blast_resistance = 12;
constexpr std::size_t g_skillnid_bleeding_resistance = 13;
constexpr std::size_t g_skillnid_blight_resistance = 14;
constexpr std::size_t g_skillnid_blindsider = 15;
constexpr std::size_t g_skillnid_bludgeoner = 16;
constexpr std::size_t g_skillnid_bombardier = 17;
constexpr std::size_t g_skillnid_bombardier_secret = 18;
constexpr std::size_t g_skillnid_botanist = 19;
constexpr std::size_t g_skillnid_bow_charge_plus = 20;
constexpr std::size_t g_skillnid_capacity_boost = 21;
constexpr std::size_t g_skillnid_capture_master = 22;
constexpr std::size_t g_skillnid_carving_master = 23;
constexpr std::size_t g_skillnid_carving_pro = 24;
constexpr std::size_t g_skillnid_cliffhanger = 25;
constexpr std::size_t g_skillnid_coalescence = 26;
constexpr std::size_t g_skillnid_coldproof = 27;
constexpr std::size_t g_skillnid_constitution = 28;
constexpr std::size_t g_skillnid_critical_boost = 29;
constexpr std::size_t g_skillnid_critical_draw = 30;
constexpr std::size_t g_skillnid_critical_element = 31;
constexpr std::size_t g_skillnid_critical_eye = 32;
constexpr std::size_t g_skillnid_critical_status = 33;
constexpr std::size_t g_skillnid_defense_boost = 34;
constexpr std::size_t g_skillnid_detector = 35;
constexpr std::size_t g_skillnid_divine_blessing = 36;
constexpr std::size_t g_skillnid_divine_blessing_secret = 37;
constexpr std::size_t g_skillnid_dragon_attack = 38;
constexpr std::size_t g_skillnid_dragon_resistance = 39;
constexpr std::size_t g_skillnid_dragonvein_awakening = 40;
constexpr std::size_t g_skillnid_dungmaster = 41;
constexpr std::size_t g_skillnid_earplugs = 42;
constexpr std::size_t g_skillnid_effluvia_resistance = 43;
constexpr std::size_t g_skillnid_effluvial_expert = 44;
constexpr std::size_t g_skillnid_elderseal_boost = 45;
constexpr std::size_t g_skillnid_element_acceleration = 46;
constexpr std::size_t g_skillnid_elemental_airborne = 47;
constexpr std::size_t g_skillnid_entomologist = 48;
constexpr std::size_t g_skillnid_evade_extender = 49;
constexpr std::size_t g_skillnid_evade_window = 50;
constexpr std::size_t g_skillnid_fire_attack = 51;
constexpr std::size_t g_skillnid_fire_resistance = 52;
constexpr std::size_t g_skillnid_flinch_free = 53;
constexpr std::size_t g_skillnid_focus = 54;
constexpr std::size_t g_skillnid_foragers_luck = 55;
constexpr std::size_t g_skillnid_fortify = 56;
constexpr std::size_t g_skillnid_free_elem_ammo_up = 57;
constexpr std::size_t g_skillnid_free_meal = 58;
constexpr std::size_t g_skillnid_free_meal_secret = 59;
constexpr std::size_t g_skillnid_frostcraft = 60;
constexpr std::size_t g_skillnid_full_bloom_gratitude = 61;
constexpr std::size_t g_skillnid_full_blooms_gift = 62;
constexpr std::size_t g_skillnid_gaias_veil = 63;
constexpr std::size_t g_skillnid_geologist = 64;
constexpr std::size_t g_skillnid_good_luck = 65;
constexpr std::size_t g_skillnid_gratitudes_blessing = 66;
constexpr std::size_t g_skillnid_gratitudes_gift = 67;
constexpr std::size_t g_skillnid_great_luck = 68;
constexpr std::size_t g_skillnid_guard = 69;
constexpr std::size_t g_skillnid_guard_up = 70;
constexpr std::size_t g_skillnid_guts = 71;
constexpr std::size_t g_skillnid_handicraft = 72;
constexpr std::size_t g_skillnid_hasten_recovery = 73;
constexpr std::size_t g_skillnid_health_boost = 74;
constexpr std::size_t g_skillnid_heat_guard = 75;
constexpr std::size_t g_skillnid_heavy_artillery = 76;
constexpr std::size_t g_skillnid_heroics = 77;
constexpr std::size_t g_skillnid_heroics_secret = 78;
constexpr std::size_t g_skillnid_honey_hunter = 79;
constexpr std::size_t g_skillnid_horn_maestro = 80;
constexpr std::size_t g_skillnid_hunger_resistance = 81;
constexpr std::size_t g_skillnid_ice_attack = 82;
constexpr std::size_t g_skillnid_ice_resistance = 83;
constexpr std::size_t g_skillnid_intimidator = 84;
constexpr std::size_t g_skillnid_iron_skin = 85;
constexpr std::size_t g_skillnid_item_prolonger = 86;
constexpr std::size_t g_skillnid_joys_gift = 87;
constexpr std::size_t g_skillnid_joys_gratitude = 88;
constexpr std::size_t g_skillnid_jump_master = 89;
constexpr std::size_t g_skillnid_latent_power = 90;
constexpr std::size_t g_skillnid_latent_power_secret = 91;
constexpr std::size_t g_skillnid_leap_of_faith = 92;
constexpr std::size_t g_skillnid_marathon_runner = 93;
constexpr std::size_t g_skillnid_master_fisher = 94;
constexpr std::size_t g_skillnid_master_gatherer = 95;
constexpr std::size_t g_skillnid_master_mounter = 96;
constexpr std::size_t g_skillnid_masters_touch = 97;
constexpr std::size_t g_skillnid_maximum_might = 98;
constexpr std::size_t g_skillnid_maximum_might_secret = 99;
constexpr std::size_t g_skillnid_minds_eye_ballistics = 100;
constexpr std::size_t g_skillnid_muck_resistance = 101;
constexpr std::size_t g_skillnid_mushroomancer = 102;
constexpr std::size_t g_skillnid_non_elemental_boost = 103;
constexpr std::size_t g_skillnid_normal_shots = 104;
constexpr std::size_t g_skillnid_nullify_wind_pressure = 105;
constexpr std::size_t g_skillnid_offensive_guard = 106;
constexpr std::size_t g_skillnid_palico_rally = 107;
constexpr std::size_t g_skillnid_paralysis_attack = 108;
constexpr std::size_t g_skillnid_paralysis_functionality = 109;
constexpr std::size_t g_skillnid_paralysis_resistance = 110;
constexpr std::size_t g_skillnid_partbreaker = 111;
constexpr std::size_t g_skillnid_peak_performance = 112;
constexpr std::size_t g_skillnid_piercing_shots = 113;
constexpr std::size_t g_skillnid_poison_attack = 114;
constexpr std::size_t g_skillnid_poison_duration_up = 115;
constexpr std::size_t g_skillnid_poison_functionality = 116;
constexpr std::size_t g_skillnid_poison_resistance = 117;
constexpr std::size_t g_skillnid_power_prolonger = 118;
constexpr std::size_t g_skillnid_pro_transporter = 119;
constexpr std::size_t g_skillnid_protective_polish = 120;
constexpr std::size_t g_skillnid_provoker = 121;
constexpr std::size_t g_skillnid_punishing_draw = 122;
constexpr std::size_t g_skillnid_quick_sheath = 123;
constexpr std::size_t g_skillnid_razor_sharp_spare_shot = 124;
constexpr std::size_t g_skillnid_recovery_speed = 125;
constexpr std::size_t g_skillnid_recovery_up = 126;
constexpr std::size_t g_skillnid_resentment = 127;
constexpr std::size_t g_skillnid_resuscitate = 128;
constexpr std::size_t g_skillnid_safe_landing = 129;
constexpr std::size_t g_skillnid_scenthound = 130;
constexpr std::size_t g_skillnid_scholar = 131;
constexpr std::size_t g_skillnid_scoutfly_range_up = 132;
constexpr std::size_t g_skillnid_sleep_attack = 133;
constexpr std::size_t g_skillnid_sleep_functionality = 134;
constexpr std::size_t g_skillnid_sleep_resistance = 135;
constexpr std::size_t g_skillnid_slinger_ammo_secret = 136;
constexpr std::size_t g_skillnid_slinger_capacity = 137;
constexpr std::size_t g_skillnid_slugger = 138;
constexpr std::size_t g_skillnid_slugger_secret = 139;
constexpr std::size_t g_skillnid_special_ammo_boost = 140;
constexpr std::size_t g_skillnid_speed_crawler = 141;
constexpr std::size_t g_skillnid_speed_eating = 142;
constexpr std::size_t g_skillnid_speed_sharpening = 143;
constexpr std::size_t g_skillnid_spread_power_shots = 144;
constexpr std::size_t g_skillnid_stamina_cap_up = 145;
constexpr std::size_t g_skillnid_stamina_surge = 146;
constexpr std::size_t g_skillnid_stamina_thief = 147;
constexpr std::size_t g_skillnid_stamina_thief_secret = 148;
constexpr std::size_t g_skillnid_stealth = 149;
constexpr std::size_t g_skillnid_stun_resistance = 150;
constexpr std::size_t g_skillnid_super_recovery = 151;
constexpr std::size_t g_skillnid_survival_expert = 152;
constexpr std::size_t g_skillnid_thunder_attack = 153;
constexpr std::size_t g_skillnid_thunder_resistance = 154;
constexpr std::size_t g_skillnid_tool_specialist = 155;
constexpr std::size_t g_skillnid_tool_specialist_secret = 156;
constexpr std::size_t g_skillnid_tremor_resistance = 157;
constexpr std::size_t g_skillnid_true_critical_element = 158;
constexpr std::size_t g_skillnid_true_critical_status = 159;
constexpr std::size_t g_skillnid_true_dragonvein_awakening = 160;
constexpr std::size_t g_skillnid_true_element_acceleration = 161;
constexpr std::size_t g_skillnid_true_gaias_veil = 162;
constexpr std::size_t g_skillnid_true_razor_sharp_spare_shot = 163;
constexpr std::size_t g_skillnid_water_attack = 164;
constexpr std::size_t g_skillnid_water_resistance = 165;
constexpr std::size_t g_skillnid_weakness_exploit = 166;
constexpr std::size_t g_skillnid_wide_range = 167;
constexpr std::size_t g_skillnid_windproof = 168;

extern const SetBonus g_setbonus_ancient_divinity;
extern const SetBonus g_setbonus_anjanath_dominance;
extern const SetBonus g_setbonus_appreciation_blessing;
extern const SetBonus g_setbonus_barioth_hidden_art;
extern const SetBonus g_setbonus_bazelgeuse_ambition;
extern const SetBonus g_setbonus_brachydios_essence;
extern const SetBonus g_setbonus_brachydios_will;
extern const SetBonus g_setbonus_commission_alchemy;
extern const SetBonus g_setbonus_deviljho_essence;
extern const SetBonus g_setbonus_diablos_ambition;
extern const SetBonus g_setbonus_full_bloom_blessing;
extern const SetBonus g_setbonus_glavenus_essence;
extern const SetBonus g_setbonus_gold_rathian_essence;
extern const SetBonus g_setbonus_guild_pride;
extern const SetBonus g_setbonus_instructors_guidance;
extern const SetBonus g_setbonus_joyful_blessing;
extern const SetBonus g_setbonus_kirin_divinity;
extern const SetBonus g_setbonus_kulve_taroth_essence;
extern const SetBonus g_setbonus_kushala_daora_flight;
extern const SetBonus g_setbonus_legiana_ambition;
extern const SetBonus g_setbonus_lunastra_essence;
extern const SetBonus g_setbonus_namielle_divinity;
extern const SetBonus g_setbonus_nargacuga_essence;
extern const SetBonus g_setbonus_nergigante_ambition;
extern const SetBonus g_setbonus_odogaron_essence;
extern const SetBonus g_setbonus_rajangs_rage;
extern const SetBonus g_setbonus_rajang_will;
extern const SetBonus g_setbonus_rathalos_essence;
extern const SetBonus g_setbonus_rathian_essence;
extern const SetBonus g_setbonus_safi_jiiva_seal;
extern const SetBonus g_setbonus_shara_ishvalda_divinity;
extern const SetBonus g_setbonus_silver_rathalos_essence;
extern const SetBonus g_setbonus_soul_of_the_dragoon;
extern const SetBonus g_setbonus_teostra_technique;
extern const SetBonus g_setbonus_tigrex_essence;
extern const SetBonus g_setbonus_uragaan_ambition;
extern const SetBonus g_setbonus_vaal_soulvein;
extern const SetBonus g_setbonus_velkhana_divinity;
extern const SetBonus g_setbonus_zinogre_essence;
extern const SetBonus g_setbonus_zorah_magdaros_essence;

extern const std::array<const SetBonus*, 40> g_all_setbonuses;

const Skill* get_skill(const std::string& skill_id) noexcept;

const SetBonus* get_setbonus(const std::string& setbonus_id) noexcept;

} // namespace

#endif // SKILLS_DATABASE_H
